import Head from 'next/head';
import styles from '@styles/Home.module.css';
import HeaderNavBar from '@components/home/HeaderNavBar';
import MainStatementSection from '@components/home/MainStatementSection';
import MainTemplateSection from '@components/home/MainTemplateSection';
import MainCarouselSection from '@components/home/MainCarouselSection';
import MainContentSection from '@components/home/MainContentSection';
//--
export default function Home() {
  return (
    <>
      <Head>
        <title>desoft.cu - Team Collaboration Software</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className={styles.header}>
        <HeaderNavBar />
      </header>
      <main className={styles.main}>
        <MainStatementSection />
        <MainTemplateSection />
        <MainCarouselSection />
        <MainContentSection />
      </main>
      <footer>footer</footer>
    </>
  );
}
